const OK_CODE = 200;
const CREATED_CODE = 201;
const ERROR_BAD_REQUEST = 400;
const ERROR_NOT_FOUND = 404;
const ERROR_SERVER = 500;

module.exports = {
  OK_CODE,
  CREATED_CODE,
  ERROR_BAD_REQUEST,
  ERROR_NOT_FOUND,
  ERROR_SERVER,
};
